###
GET /API/1/users HTTP/1.1
Host: 127.0.0.1:3000
Content-Type: : application/json
//400
###
GET /API/1/ HTTP/1.1
Host: 127.0.0.1:3000
//200
###
POST /API/1/comments HTTP/1.1
Host: 127.0.0.1:3000
Content-Type: application/json

{
    "comments" : ["some new comment", "enother_comment"]
}
//200
###
POST /API/1/comments HTTP/1.1
Host: 127.0.0.1:3000
Content-Type: application/json

{
    "comments" : ["Like this video!"]
}
//200
###
POST /API/1/comments HTTP/1.1
Host: 127.0.0.1:3000
Content-Type: application/json

{"username": "Vlad","comments":["hello", "Where is my sosages?", "LOL"]}
//200
###
POST /API/1/comments HTTP/1.1
Host: 127.0.0.1:3000
Content-Type: application/json

{
"username": "Vlad",
"comments":["hello, Everyone"]
}
//200
###
GET /API/1/stats HTTP/1.1
Host: 127.0.0.1:3000
Content-Type: text/html
//200

###
GET /login/None HTTP/1.1
Host: 127.0.0.1:3000
Content-Type: text/html
//400
###
GET /API/1/login?password=secret HTTP/1.1
Host: 127.0.0.1:3000
Content-Type: text/html
//200
###
GET /API/1/login?password=letMeIn&login=vlad HTTP/1.1
Host: 127.0.0.1:3000
Content-Type: text/html
//403

// /API/1/login/;ajfoJFO;f;/profile
// /API/1/cats/vasya/health


// '/login'
// '/login/:catName/profile'

###
GET /API/1/about HTTP/1.1
Host: 127.0.0.1:3000
Content-Type: text/html

###
GET /API/1/about?password=secret HTTP/1.1
Host: 127.0.0.1:3000
Content-Type: text/html

###
GET /API/1/about?password=letMeIn HTTP/1.1
Host: 127.0.0.1:3000
Content-Type: text/html