###
GET /API/1/users HTTP/1.1
Host: 127.0.0.1:3000
Content-Type: : application/json
###
GET /API/1/ HTTP/1.1
Host: 127.0.0.1:3000
###
POST /API/1/comments HTTP/1.1
Host: 127.0.0.1:3000
Content-Type: application/json

{
    "comments" : ["some new comment", "enother_comment"]
}
###
POST /API/1/comments HTTP/1.1
Host: 127.0.0.1:3000
Content-Type: application/json

{
    "comments" : ["Like this video!"]
}
###
POST /API/1/comments HTTP/1.1
Host: 127.0.0.1:3000
Content-Type: application/json

{"comments":["hello"]}
###
GET /API/1/stats HTTP/1.1
Host: 127.0.0.1:3000
Content-Type: text/html